### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [foxoter/regExp#2]
Хорошая работа, нужно сделать не большие исправления, что бы была корректная валидация примеров ниже.

**Отлично**
- эфективное регулярное выражение
- оформленное readme.md
- нет лишних файлов в репозитории
- требования к веткам соблюдены

**Нужно исправить**
- Валидация по email пропускает все имайлы, прошу проверить
- `example@yandex` - не хватает верхнего уровня домена
- `example@привет` - разрешается только a-z
- `den~test@gmail.com` - Проходят валидацию не корректные адреса с доп символами
- `den!s@gmail.com` - Проходят валидацию не корректные адреса с доп символами
- `+7(925)900-90-9099` - на одну цифру больше чем положено
- `+7(925)900-90-` - на одну и более цифр меньше чем положено
- `+7(925)900-90-0` - на одну и более цифр меньше чем положено
- `+7 925--900--90-90` - между секциями дефис должен встречаться только в одном экземпляре
- `http://google.ru///1///2///3` - количество слешей в пути должно быть ограничено одним экземпляром для каждой части пути
- `http://ya.ru:00000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)
- `http://11.11.11.11:0000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)

**Можно лучше**
- С комитами все отлично, но можно немного лучше. Часто возникает соблазн написать комментарий к коммиту вида "fixes" или "first commit". Лучше описывать коммиты подробнее.
Делать коммиты, когда:
1) выполнил единицу работы
2) сделал изменения, которые потом может потребоваться отменить
Интересная статья по [ссылке](https://habr.com/ru/company/Voximplant/blog/276695/)

**Comment by foxoter** [comment]
Замечания исправил, архив на платформе тоже обновил. Спасибо!

**Comment by talantbekov123** [comment]
Хорошая работа, все комментарии исправлены! Похвально! Принимаю.
